### ISSUE TITLE
Correct syntax highlighting for all languages

### ISSUE THREAD

**Issue by grantmcdermott** [LOST-STATS/lost-stats.github.io#3]
Currently, native syntax formatting only works for some languages (Python, R, SAS). Other languages like Stata, Matlab, GRETL, etc. are just formatted as plain text chunks. See here for some examples: https://lost-stats.github.io/Model_Estimation/ordinary_least_squares.html#implementations

Do we need to add syntax support for these other languages? (Maybe from Pygments or some other source?)

**Comment by NickCH-K** [comment]
Adding this support would be a big improvement I think, if possible. LOST should be open to lots of different languages, so it makes sense to have support for highlighting them.

**Comment by khwilson** [comment]
IIRC, Github Pages uses Linguist for its language rendering, which supports this list of languages: https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

The matlab rendering problem was that you need to spell matlab as either `MATLAB` or `matlab` not `Matlab`. OTOH, I don't know what's going on with the stata renderer. Ostensibly, linguist supports it but I can't get it to work for the life of me.... Let's see if it works here:

```stata
regress mpg headroom trunk weight
```

**Comment by khwilson** [comment]
Well, that seems to work-ish. The bundle it's using is here: https://github.com/pschumm/Stata.tmbundle

My guess is there's something funny going on with that bundle. It hasn't been touched since 2015.....

**Comment by khwilson** [comment]
Looked into this a bit more. Seems like the issue is that Github Pages uses the base rouge package: https://github.com/rouge-ruby/rouge

Whereas Github proper uses the Linguist package. :/

Moreover, base github pages does _not_ support extra plugins. Thus, there are two ways to approach this problem:
* You could attempt to shepherd a Stata lexer through the rouge PR process. Here's a lexer: https://github.com/khwilson/rouge/commit/0f8722d44ecff028293d15f7d35d16d5f1c81078 Seems like they only have one maintainer and he's several months behind on proposed lexers.
* You could move the build process to CircleCI and then have all the plugins you want. :)

**Comment by grantmcdermott** [comment]
Nice detective work @khwilson.
 
You're in better position to judge (and execute!) this than me, but my quick thoughts:

- Any reason not to submit your current lexer as a PR (i.e. as is)? I know it may take a while for the maintainer to get to it, but seems like a good idea regardless.
- CI is a great idea and should also help with some of the testing that we've been talking about in #6. Seems like kind of a heavy lift, though? My bandwidth is going to be very limited over the next few weeks. Is this something you'd be able to take on by yourself? (Ofc feel free to bring on whoever else you think appropriate.)

**Comment by khwilson** [comment]
As long as you don't mind some of my esoteric gulpfiles lying around, then the CI isn't that heavy of a lift. Should take me like 30mins in an evening.

**Comment by NickCH-K** [comment]
That would be amazing. I don't have any problem with gulpfiles. This is really incredible work.

**Comment by khwilson** [comment]
Okiedokes I have the gulp stuff setup locally. However, due to a quirk of gh-pages, I need to clobber the master branch of this repo, specifically the gh-pages for the repository with the same name as the org _must_ run its gh-pages off the master branch. :/

So I propose the following:
* Y'all finish up whatever thing you're doing locally.
* Push by 9pm Eastern tomorrow (Thursday).
* I'll make a backup copy of the repo (I'll just make a copy in this same org)
* Then I'll do the big push at ~9:30.
* I then shall debug until done (hopefully all goes well :) )
* From then on, you need to do your work on the `source` branch.

If @grantmcdermott and @NickCH-K approve I can just push that tomorrow evening.

**Comment by NickCH-K** [comment]
Sounds good, I'll leave it alone for a bit. I'm not planning any more pushes until this weekend anyway when I'll write another page.

**Comment by grantmcdermott** [comment]
Sounds good to me! Thanks Kevin.

**Comment by khwilson** [comment]
Hi all,

Just a reminder that I'm going to pull the trigger on the conversion at
9:30 tonight so get your patches in. :)

Kevin

**Comment by khwilson** [comment]
Oops. @grantmcdermott can you make me an org owner temporarily? I need it to enable the circleci builds.

**Comment by grantmcdermott** [comment]
@khwilson done!

(You and @NickCH-K.)

**Comment by khwilson** [comment]
Okiedokes. The circleci job is now setup and running. https://circleci.com/gh/LOST-STATS/lost-stats.github.io And pushing to master!!

If you're working locally, please switch your branch to the `source` branch and push there. If you're working on the website, I've changed the default branch to `source` so things should be correct by default. :)

After you all confirm this is working for you, I'll fix the syntax highlighting stuff. :)

**Comment by grantmcdermott** [comment]
Amazing. Kevin, you're a boss.

Have at the syntax stuff and then feel to close once you're happy.

**Comment by khwilson** [comment]
Okiedokes, Stata highlighting is now online with my jank lexer. It's having issues passing rouge's tests due to weird whitespace issues (Stata's `*` comments are weird). So I'm going to put away the shepherding that through rouge's PR process. I'm also going to close issue and have a "write GRETL lexer" issue.
